### PR TITLE
make argc/argv accessible through fire

### PR DESCRIPTION
**Pull request by nholthaus**
I've been using `fire-hpp` in production, and it's an awesome library, thank you for creating this!

One thing I've noticed is that a lot of frameworks with which I'd want to use fire (Qt, various loggers) require access to argc and argv. My workaround has been to break open the `FIRE` macro and copy argc/argv into file scoped variables, but I think that's undesirable, especially as the macro continues to get more complex with additional development.

Although in many cases you shouldn't need them, I think it makes sense for `fire` to provide access to argc/argv through some static variables or functions in the fire namespace, so that users will be able to use the fire macros as intended even when mixing frameworks.

This PR represents a possible implementation.

### CODE REVIEW

**Comment by kongaskristjan** [comment]
Thanks, great idea! I'll review this within 36 h or so.

**Comment by kongaskristjan** [comment]
The problem that I currently see is that fire doesn't know what arguments eg. Qt accepts (I assume it accepts something as it requires argc and argv). So, if these arguments are used from the command line, fire will exit with error even before fired_main() has a chance to do anything.

One solution is to implement interface that allows something like:
`int fired_main(bool flag = fire::arg("--some-flag"), fire::args = fire::args()) {}`.

Here fire::args contains argv and argc. This would also signal the fire library to not emit errors when additional options are specified from the command line (because apparently the user prefers to do some processing himself).

**Comment by nholthaus** [comment]
sounds good to me.

**Comment by kongaskristjan** [comment]
Sorry for disappearing, motivational issues start creeping in (not a good sign for the project lol). Though I guess the additional time allowed settling to a better interface in the end.

4b09ac3f143f36f2e5431cfda1008cee9df09e42 (master) should now have a working implementation. See [raw args](https://github.com/kongaskristjan/fire-hpp#raw_args) and [FIRE_ALLOW_UNUSED](https://github.com/kongaskristjan/fire-hpp#fire) for documentation.

**Comment by nholthaus** [comment]
thanks!

I maintain a few open source libraries myself, I know the feeling.

**Pull request closed without merging**
