### PR TITLE
Standard cpp structure

### PR DESCRIPTION
**Pull request by cxkoda**
Move `fire.hpp` to `include/fire/fire.hpp` in order to make it consistent with the inofficial standard.
Introduce a fire target to simplify the test and example compilation.

### CODE REVIEW

**Comment by kongaskristjan** [comment]
Thanks for interest in contributing!

However, this structure makes sense for larger projects, while this is (and remains for the foreseeable future), a single-header library. Currently it just hides fire.hpp behind two directories.

Also, as the change only adds/changes lines of code, it's a little hard to see it as a simplification.

**Comment by cxkoda** [comment]
Hi again :)
The `include/fire/fire.hpp` has two advantages for people coming from the outside (as it was the case for me):
  - People in the c++ community tend to look for an `include` directory first. With this, it is immediately clear which directory has to be included by the compiler.
  - The subfolder adds intention to the header inclusion and avoids name collisions. I.e. a user now has to state `#include "fire/fire.hpp"` instead of `#include "fire.hpp"`, where the latter is more likely to collide with a header file of the user. 

I did notice that every cmake-target for the examples include `fire.hpp` as a source file, located at `../fire.hpp`.
It is more idiomatic to define an interface-library and link that library to your executables. In this way, you have to specify the location of the header only once (which I changed for this PR) and the rest is handled by cmake itself. This becomes more important in the inclusion of this project in other cmake-projects as pointed out in #4.

**Comment by cxkoda** [comment]
Please keep in mind, that this PR is only cosmetical :) In the end the `include/fire/fire.hpp` is only a matter of taste.
However, to abstract away one's personal taste it is important to export a cmake-library, which defines what has to be included.

**Comment by kongaskristjan** [comment]
> In the end the include/fire/fire.hpp is only a matter of taste.

I guess my taste likes the current structure more :D, and exporting the target was done in your other PR anyway. Thus I'll close this PR for now, but feel free to comment if you think I missed something important.

**Comment by axalon900** [comment]
I was about to open a very similar pull request before realizing that this came up before, so I'll add my two cents.

Not doing something like this makes it difficult to package and consume in a standard fashion. If you don't provide a canonical install schema, people will make them up, which becomes an issue when people (like me) try to package your library for a package manager.

As it stands, to use your library, you either:

1. Copy the header into your library directly and `#include "path/to/fire.hpp"`
2. Add the project as a subdirectory and in your CMakeLists do `add_subdirectory(fire-hpp)` + `target_link_libraries(<target> fire)`, then `#include <fire.hpp>`
3. Package it with Conan and, depending on how it gets consumed:
    * Using Conan's `cmake` generator and using `target_link_libraries(<target> CONAN_PKG::fire)`
    * Using Conan's `cmake_find_package` generator and, since there's no prescribed "official" scheme:
        * If the package is called "fire-hpp": `find_package(fire-hpp)` + `target_link_libraries(<target> fire-hpp::fire-hpp)`
        * If the package is called "fire": `find_package(fire)` + `target_link_libraries(<target> fire::fire)`

On top of that it's usually bad to have a library's header files at the root-level, so the packager then will invent a folder to put it in, meaning different users will need to write `#include <fire/fire.hpp>`, `#include <fire-hpp/fire.hpp>`, or even still just `#include <fire.hpp>`. The point is that all these methods are pretty divergent which means more stuff to change when you move from one to the other. Maybe it doesn't seem like that big a deal for a small library like this but it's actually a pretty simple change to make on this end, so why not? Making the build and install include paths consistent is step one, and a naked header file without a subdirectory isn't really acceptable in an installed situation. The remainder is to add install() commands and an export file that `find_package()` can use. For a single-header-only library, it's pretty trivial. Once all that's defined, it's easy enough to ensure that each consumption method (well, besides "copy the header") keeps the same semantics (i.e. same target name, same install path), which sounds like a very good thing to me in terms of usability.

**Comment by cxkoda** [comment]
@axalon900 I fully agree with the things you pointed out. Since I rarely install header-only libs this divergence didn't cross my mind at the time of opening the PR - but it is a crucial point. The different results produced by the different methods will in the long run confuse many users. Since the project is still quite young it is still easy to introduce these changes without breaking too much stuff - so I also think, why not make it standardised from the start and save the pain of probably transitioning later.

**Comment by axalon900** [comment]
Hey it got reopened! I guess I made a good case? 😁

If this is back in the running, there is one outstanding issue. I opened PR #7 which adds install commands, but it uses `fire-hpp/` as the header folder rather than `fire/`. My thinking was that "fire" might be a bit too ambiguous and that adding "-hpp" would both match the repository name as well as distinguish it as a C++ library. It fits with other libraries which include "cpp" in their name and "hpp" also hints at its single-header-only nature. If that sounds good to you all, should we change this PR to match? Otherwise I can switch mine to use `fire/`. Either way, it's best that we have them in sync.

**Comment by kongaskristjan** [comment]
I agree with the recent arguments made here. The reason I like fire.hpp at root level is purely aesthetic, but having different paths depending on installation can really be a pain in the neck. I'll have more time in the weekend, if everything is fine I'll probably merge this during the weekend. I'll then look into #7 also.

**Comment by kongaskristjan** [comment]
> If that sounds good to you all, should we change this PR to match?
Yes, this should be changed fire-hpp/.

**Comment by cxkoda** [comment]
Hi together, sorry for the late reply and thanks for reopening the PR. I agree, `fire-hpp/` might be the better fit - I will change the PR accordingly.

**Comment by cxkoda** [comment]
Done and ready for review :)

**Comment by cxkoda** [comment]
I just realised I was a little to eager and changed the cmake project and target name to `fire-hpp` as well, which will lead to conflicts with #7. Should we keep everything at `fire-hpp` for consistency and synchronize #7 or should I revert back to the old naming? What do you think?

**Comment by axalon900** [comment]
I don't have a particularly strong opinion. It's mostly just aesthetic except for a minor detail in packaging for Conan. Renaming the target to `fire-hpp` would remove the need to specify a separate component called `fire` to keep parity with the "stock" layout. By default, Conan's generated Findfire-hpp.cmake will export a single target for the whole package called `fire-hpp::fire-hpp`, so if that just happens to line up with a stock install, great. On the other hand it's pretty trivial to define that component and to me `fire` is a little more pleasing as a target name, so it really just comes down to taste.

**Comment by axalon900** [comment]
Either way I'll need to make adjustments to #7 since it is still expecting fire.hpp to be in the root folder.

**Comment by kongaskristjan** [comment]
>>> Should we keep everything at fire-hpp for consistency?

Yes.

One bonus for `fire-hpp` name is also that if someone comes up with Fire for C (probably using macro-madness), name conflicts are more easily avoided. This isn't entirely impossible, as there has been interest in having something similar in haskell too (as pointed out in comments, there is options-generic, which, judging from examples, is very similar to fire-hpp) (https://www.reddit.com/r/haskell/comments/i6iwvk/haskellfire/).

**Pull request merged**
